name: melos_package_maintainer

packages:
  - packages/hello_package/
  - packages/zen_package/

scripts:
  analyze:
    exec: dart analyze .
  
  vsa:
    exec: version -a


command:
  version:
    branch: main # Only allows versioning to happen on the main branch
    releaseUrl: true
    # hooks:
    #   precommit:

